services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${DB_NAME} -U ${DB_USER}
      interval: 15s
      timeout: 20s
      retries: 10
    ports:
      - "5432:5432"
volumes:
  pg-db: