ALTER TYPE "ROLE" RENAME TO ROLE_ENUM;

CREATE CAST (varchar AS ROLE_ENUM) WITH INOUT AS IMPLICIT;

ALTER TABLE "User"
    ALTER COLUMN lastName DROP NOT NULL;

ALTER TABLE "User"
    ALTER COLUMN firstName SET NOT NULL;

ALTER TABLE "User"
    ALTER COLUMN role TYPE ROLE_ENUM